import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import AuthProvider from "@/app/providers/auth";
import { Toaster } from "@/app/components/ui/sonner";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "SFC: Smart Finance Calculator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${poppins.className} flex min-h-screen w-full flex-col antialiased xl:flex-row`}
      >
        <AuthProvider>{children}</AuthProvider>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
